<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MONO-HYD-LAP-12" name="testClasses.TC004_PUT_EmployeeRecord" tests="5" failures="1" timestamp="24 Nov 2019 10:44:57 GMT" time="0.090" errors="0">
  <testcase name="checkServerType" time="0.010" classname="testClasses.TC004_PUT_EmployeeRecord">
    <failure type="java.lang.AssertionError" message="expected [Apache] but found [nginx/1.16.0]">
      <![CDATA[java.lang.AssertionError: expected [Apache] but found [nginx/1.16.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at testClasses.TC004_PUT_EmployeeRecord.checkServerType(TC004_PUT_EmployeeRecord.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- checkServerType -->
  <testcase name="checkStatusLine" time="0.004" classname="testClasses.TC004_PUT_EmployeeRecord"/>
  <testcase name="checkContentType" time="0.021" classname="testClasses.TC004_PUT_EmployeeRecord"/>
  <testcase name="checkResponseBody" time="0.051" classname="testClasses.TC004_PUT_EmployeeRecord"/>
  <testcase name="checkStatusCode" time="0.004" classname="testClasses.TC004_PUT_EmployeeRecord"/>
</testsuite> <!-- testClasses.TC004_PUT_EmployeeRecord -->
